- hosts: aipo8110
  sudo: yes
  user: vagrant
  vars:
    usr_local: "/usr/local" 
    aipo_filename: "aipo-8.1.1-linux-x64.tar.gz" 
    aipo_installer_dir: "aipo-8.1.1-linux-x64" 
    aipo_install_url: "https://osdn.jp/frs/redir.php?m=iij&f=%2Faipo%2F64847%2Faipo-8.1.1-linux-x64.tar.gz" 
  tasks:
    - name: install gcc
      yum: name=gcc state=latest

    - name: install nmap
      yum: name=nmap state=latest

    - name: install lsof
      yum: name=lsof state=latest

    - name: install unzip
      yum: name=unzip state=latest

    - name: install readline-devel
      yum: name=readline-devel state=latest

    - name: install zlib-devel
      yum: name=zlib-devel state=latest
            
    - name: unarchive aipo
      unarchive: src={{ aipo_install_url }} dest={{ usr_local }} copy=no
      
    - name: install aipo
      command: sh installer.sh chdir={{ usr_local }}/{{ aipo_installer_dir }}
      register: ls_result

    - debug: var=ls_result.stdout_lines
      when: ls_result | success
      
    - name: startup aipo
      command: "{{ usr_local }}/aipo/bin/startup.sh"
      async: 15
      poll: 0
      register: ls_result

    - debug: var=ls_result.stdout_lines
      when: ls_result | success
